README.md
deploy/crds/neutron_v1_neutronovsagent_cr.yaml
deploy/crds/neutron_v1_neutronsriovagent_cr.yaml

Updated to use docker.io/tripleotrain/rhel-binary-neutron* images
with the current-tripleo tag.

Updates to doc and cr

---

pkg/controller/neutronovsagent/neutronovsagent_controller.go
pkg/neutronovsagent/configmap.go
templates/common.sh
templates/openvswitch_agent_init.sh

Introduced templates/common.sh and templates/openvswitch_agent_init.sh
to run the container init tasks and run openvswitch_agent_init.sh with
the volume which stores the rendered configuration as parameter. The
init scripts are stored in its own configmap which allows us to mount
then with a different mask.
common.sh is intended to be a common functions lib for all the init
tasks for the neutron-operator.

Split off init tasks

---

deploy/role.yaml
tools/csv-generator.go

This fix the issue where the ServiceMonitor object create on
operator start fails with:
{"level":"info","ts":1592920265.5644455,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"servicemonitors.monitoring.coreos.com \"neutron-operator-metrics\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}

Fix role to allow set finalizer

---

Dockerfile
Dockerfile.rhel

- use ARG's for variants between the 2 files
- Dockerfile.rhel is intended to build in
OSBS using cachito external sources bundle
- dropped CGO_ARCH and target from building
- copy all of the source in and then setup
for copying into final image
- go builds should be statically linked now
- crds are copied into a bundle folder first
and then copied as a whole into final image
- Dockerfile should continue to work as
expected for local builds
- Dockerfile.rhel should work for building downstream

Rework Dockerfile and add Dockerfile.rhel

---

Makefile
api/bases/neutron.openstack.org_neutronapis.yaml

With the new api sub module, consumer operators just have to import the api submodule. For envtest it is required to install CRD for e.g. keystone-operator and mariadb-operator to be able to use it.
Moving the directory config/crd/bases which holds the generated files in to the api module that they are available with the module and link the dir in the original place does not work as kustomize autodetect fails on symlinked directories [1].
This updates the `generate` Makefile target to copy config/crd/bases to /api on successful generation run.
[1] kubernetes-sigs/kustomize#1886

Copy rendered CRD files dir to /api/bases in make manifests

---

controllers/neutronapi_controller.go

We should only attempt to add finalizers in reconcileNormal() if they are missing from the instance being reconciled, and if such action is needed, we should end that reconcile after updating the instance to avoid potentially reconciling again with an outdated version of the instance (see [1] for details).
[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/1#discussion_r997014701

Only add finalizer and update instance if necessary

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml

When a CRD has an optional struct field the defaulting of that field needs special care. Both the field with the struct type need a full default value defined and each individual subfields in the struct needs default value defined. Otherwise in the first reconcile call the PasswordSelectors is empty and then in the second reconcile it is filled.
Now documented via https://github.com/openstack-k8s-operators/docs/pull/12

Fix defaulting PasswordSelectors

---

config/rbac/role.yaml
controllers/neutronapi_controller.go

Previous commit wrongly set it to ovndbcluster,
it should be "ovndbclusters" instead.

Fix rbac for OVNDBCluster

---

controllers/neutronapi_controller.go
go.mod
go.sum
main.go

Required with the switch in ovn-operator [1].
[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/3

Switch to v1beta1 version for ovn

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
config/samples/neutron_v1beta1_neutronapi.yaml

This change makes the container image optional and sets
the default to use the stable/zed image.

use stable/zed containers

---

pkg/neutronapi/deployment.go

Neutron server sometimes takes time to start
as multiple workers needs to be started and also
slow infra can further delay it.
After 3(Default failureThreshold) liveness probe failures pod get's restarted and can stuck into restart loop. With this patch increasing initial delay to 20s for both liveness and readyness probes and
also increase periodseconds to 5s in liveness probe.
Not removing TODO comment from the probes as we would tune these further later.

Update initial delay for probes

---

go.mod
go.sum
main.go

The default value for the zap logger is using epoch timestamps, but that's not user friendly, so we are changing it to using the ISO8601 time format instead.
The zap package from uber is already a dependency from the zap module of the controller-runtime package we already use, so we are not adding any new dependency.
Signed-off-by: Yatin Karel <ykarel@redhat.com>

Logging: Use ISO8601 timestamps

---

templates/neutronapi/config/neutron.conf

We enable metadata service in compute nodes by
default, and in order to have metadata/dhcp
port created with networks we require to set
config option [ovn]/ovn_metadata_enabled to True.

Set ovn_metadata_enabled to True by default

---

controllers/neutronapi_controller.go
templates/neutronapi/config/neutron.conf

Internal endpoint is meant for interaction between services. This ensures neutron uses internal endpoints when it sends requests to the other services.

Use internal endpoint to interact with Keystone/Nova

---

templates/neutronapi/config/neutron.conf

This option was already removed from Neutron during Zed cycle[1].
[1] https://review.opendev.org/c/openstack/neutron/+/837286

Drop removed [DEFAULT] allow_overlapping_ips

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
config/samples/neutron-secret.yaml
pkg/neutronapi/dbsync.go
pkg/neutronapi/deployment.go
pkg/neutronapi/initcontainer.go
templates/neutronapi/bin/init.sh
templates/neutronapi/config/neutron.conf

... instead of nova user. This allows us to reduce dependency on the resources managed by nova-operator and better separate each operators. The credential should work fine as long as the user has admin access with the 'service' project scope.

Use own user to send admin requests to nova

---

controllers/neutronapi_controller.go

The current logic ignores the error but it should be returned so that the error can be detected in the reconciler.

Return error in ConfigMap creation

---

kuttl-test.yaml
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/cleanup-neutron.yaml
test/kuttl/common/deploy_neutron.yaml
test/kuttl/common/errors_cleanup_neutron.yaml
test/kuttl/tests/neutron_scale/01-assert.yaml
test/kuttl/tests/neutron_scale/01-deploy-neutron.yaml
test/kuttl/tests/neutron_scale/02-assert.yaml
test/kuttl/tests/neutron_scale/02-scale-neutronapi.yaml
test/kuttl/tests/neutron_scale/03-assert.yaml
test/kuttl/tests/neutron_scale/03-scale-down-neutronapi.yaml
test/kuttl/tests/neutron_scale/04-assert.yaml
test/kuttl/tests/neutron_scale/04-errors.yaml
test/kuttl/tests/neutron_scale/04-scale-down-zero-neutronapi.yaml
test/kuttl/tests/neutron_scale/05-cleanup-neutron.yaml
test/kuttl/tests/neutron_scale/05-errors.yaml

These tests cover basic operations: deployment, scale up, scale down and clean up.
The tests use code from the install_yamls repo to reuse some operations like
the deployment of the neutron operator, as well as the cleanup from previous runs.
Test are thought to be run from the `install_yamls` repo, see the following
PR: https://github.com/openstack-k8s-operators/install_yamls/pull/99
There are three ways to run the tests:
1) Run `make neutron_kuttl`, this will only work if you want to run the test
from the master branch.
2) Run `make neutron_kuttl NEUTRON_REPO=ovs-operator._repo_url
NEUTRON_BRANCH=branch_name` this is useful if you want to run the tests from
a fork
3) Run `make neutron_kuttl
NEUTRON_KUTTL_CONF=/path/to/neutron-operator/kuttl-test.yaml …

Add basic KUTTL tests for neutron-operator

---

.github/workflows/build-neutron-operator.yaml

We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.

Drop paths-ignore from build operator workflow

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml

Otherwise marshalling/unmarshalling CRDs with webhooks results in error
as it serializes these struct fields as "null".
`The KeystoneAPI "keystone" is invalid: spec.networkAttachmentDefinitions:
Invalid value: "null": spec.networkAttachmentDefinitions in body must be of
type array: "null"`

Add omitempty tag for slices

---

.github/workflows/build-neutron-operator.yaml

We are hitting rate-limt during post merge image build:
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
It seems it is coming from [1] and can be fixed by passing the GITHUB_TOKEN there. So this patch does that to avoid build failures due to rate-limit.
[1] https://github.com/kubernetes-sigs/kustomize/blob/0fd385d7197026b92272dc8688ec66593be91fba/hack/install_kustomize.sh#L145

Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

---

.pre-commit-config.yaml
Makefile
test/kuttl/common/assert_sample_deployment.yaml

Updating pre-commit hook with make. pre-commit-golang repo is no longer maintained[1]. Instead of using
unmaintained repo we can use make to run pre-commit.
[1] https://github.com/dnephin/pre-commit-golang/issues/98

Run pre-commit with make

---

controllers/neutronapi_controller.go
go.mod
go.sum
test/functional/base_test.go
test/functional/neutronapi_controller_test.go

With patch [1] ovnclient will expose internal (POD network) and edpm (external network). This patch adopts neutron-operator for that change.
Requires: https://github.com/openstack-k8s-operators/ovn-operator/pull/32
[1] https://github.com/openstack-k8s-operators/ovn-operator/pull/32

Use new internal-DB addresses exposed by ovnclient

---

test/kuttl/common/cleanup-neutron.yaml
test/kuttl/common/deploy_neutron.yaml
test/kuttl/tests/neutron_scale/01-deploy-neutron.yaml
test/kuttl/tests/neutron_scale/deploy/kustomization.yaml

Instead of using install_yamls targets for deploying and cleaning up
neutron, use the CR sample from config/samples. This removes a possible
circular dependency issue when using install_yamls to run the jobs and
to run some test steps.

Remove install_yamls dependency for kuttl tests

---

Makefile

This is required when running operator locally and has been added to some other operators already such as [1]
[1] https://github.com/openstack-k8s-operators/glance-operator/blob/master/Makefile#L147

Add local templates export to MakeFile

---

pkg/neutronapi/const.go

The constant has not been used since we stopped creating admin endpoint.

Remove unused constant for admin endpoint

---

Makefile
README.md
config/default/manager_default_images.yaml
config/samples/neutron_v1beta1_neutronapi.yaml
test/kuttl/common/assert_sample_deployment.yaml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

renovate.json

renovate bot was not running yet and is being enabled with [1], renovate.json was missing some recent fixes that is done in other operators. This patch syncs it.
[1] https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci/pull/83

Update renovate.json to latest updates

---

.github/workflows/build-neutron-operator.yaml

In line with Red Hat's commitment to use inclusive language in our products. This change renames the default branch from master to main.

Change master branch to main

---

api/v1beta1/neutronapi_types.go
controllers/neutronapi_controller.go

This ensures the Ready Condition is reset when CR becomes once ready but something fails during reconfiguration.

Reset Ready condition when update failed

---

pkg/neutronapi/volumes.go
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml

Timezone can be configured by TZ environment and this is more flexible. (For example users can configure different timezone for pods and platform.)
Also, mounting machine-id does not guarantee unique id in pods because we do not strictly prohibit running multiple pods in the same node.

Remove HostPath volume mounts

---

config/manifests/bases/neutron-operator.clusterserviceversion.yaml

This should hide the neutron package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

CSV: Set operator-type: non-standalone

---

controllers/neutronapi_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

Makefile

https://github.com/openshift/release/pull/41169 was merged which resolves the permission problem in CI. Thus we can revert the change and use the consistent command.

Use consistent commands to copy manifests

---

templates/neutronapi/config/neutron.conf
test/functional/neutronapi_controller_test.go

This change limits the neutorn server to 2 api workers
and 1 RPC worker by default.
Closes: #164

limit neutron server workers by default

---

OWNERS_ALIASES

He is still able to approve the PRs but
seems that's happening as he is part of the
admin group[1] for this repo.
[1] https://github.com/orgs/openstack-k8s-operators/teams/network

Include Ihar in network-approvers

---

kuttl-test.yaml
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/cleanup-neutron.yaml
test/kuttl/common/errors_cleanup_neutron.yaml
test/kuttl/tests/neutron_scale/01-deploy-neutron.yaml
test/kuttl/tests/neutron_scale/02-assert.yaml
test/kuttl/tests/neutron_scale/02-scale-neutronapi.yaml
test/kuttl/tests/neutron_scale/03-assert.yaml
test/kuttl/tests/neutron_scale/03-scale-down-neutronapi.yaml
test/kuttl/tests/neutron_scale/04-assert.yaml
test/kuttl/tests/neutron_scale/04-scale-down-zero-neutronapi.yaml
test/kuttl/tests/neutron_scale/deploy/kustomization.yaml

Modify the kuttl tests so that they can run in any namespace, not just
in the openstack one. This requires removing any mention of the
namespace in the asserts and using the $NAMESPACE variable in scripts
instead of the namespace name.
Needs https://github.com/openstack-k8s-operators/install_yamls/pull/458 to be merged for kuttl job in CI to pass.

Change kuttl tests to run in any namespace

---

Makefile
test/functional/neutronapi_controller_test.go

It would be more clean setting in Makefile
instead of hard coding relative path in the
test code.
Also drop OPERATOR_TEMPLATES default from run
target as it's no longer needed since [1].
[1] https://github.com/openstack-k8s-operators/lib-common/pull/200

Set OPERATOR_TEMPLATES for tests in Makefile

---

hack/configure_local_webhook.sh

The script currently fails on systems where
firewall-cmd binary do not exist. Let's set the
firewall rules only when binary exists.

[local webhook] Adjust firewall only if binary exists

---

.github/create_bundle.sh
.prow_ci.env
api/v1beta1/neutronapi_types.go
config/default/manager_default_images.yaml
config/manifests/bases/neutron-operator.clusterserviceversion.yaml
test/kuttl/common/assert_sample_deployment.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
(NOTE: this currently requires a secure registry)

Support disconnected network environments

---

controllers/neutronapi_controller.go
pkg/neutronapi/const.go
templates/dhcp-agent.conf
test/functional/neutronapi_controller_test.go

The config is (right now) exactly the same as for sriov agent. But we still want to keep the secrets separated, if nothing else - to keep key names and secret names meaningful and explicit.

Create config Secret for DHCP agent

---

go.mod
go.sum
test/functional/neutronapi_controller_test.go
test/functional/suite_test.go

This is necessary to remove a dependency cycle from lib-common

[envtest]Use database helpers from mariadb-operator

---

test/functional/neutronapi_controller_test.go

It was wrongly checking for InputReady condition
to be False and it was working as for sometime
condition is False while the secret is not created.
Fixed the order of secret creation and Simulating
TransportURL and expect InputReady Condition to be True.

Fix Envtest check for input ready with TransportURL

---

controllers/neutronapi_controller.go

After recent changes that removed kolla from the startup path, the code that calculated new hash values was moved from the main reconcileNormal into reconcileInit subroutine. This made immediate return on input hash change from reconcileInit not to circumvert further loop execution, as was before the patch, but instead to proceed with the execution of the "main" procedure, incl. creating the neutronapi Deployment.
This behavior resulted in neutronapi startup before the db was initialized, which could be observed as failure of the API container with error messages about missing tables in neutron database.
This patch explicitly requests a Requeue on input hash change, which stops the current loop execution before the Deployment is created.
Note: it is unclear how to validate the fix in test …

Wait for db-sync completion before creating neutronapi Deployment

---

config/rbac/role.yaml
controllers/neutronapi_controller.go
pkg/neutronapi/const.go
pkg/neutronapi/dbsync.go
pkg/neutronapi/deployment.go
pkg/neutronapi/scc.go
pkg/neutronapi/volumes.go
test/kuttl/common/assert_sample_deployment.yaml

Now that we removed kolla bits from the startup path, we can unprivilege the containers.
Note: since we still may mount HostPaths, we have to stick to hostmount-anyuid for now. If this interface is revisited and e.g. switched to PVCs, then we should be able to tighten SCC a bit more.

Run neutronapi / db-sync as neutron:neutron

---

templates/neutronapi/config/01-neutron.conf

Currently only geneve tenant networks are allowed, open up it to allow other network types to be created by default.

Update tenant_network_types to allow other types to be created

---

templates/neutronapi/config/01-neutron.conf
test/functional/neutronapi_controller_test.go

It is required to be set for multi master galera, without it set there can be reads from not up to date db instance and that leads to various issues.

Enable mysql_wsrep_sync_wait galera db option

---

controllers/neutronapi_controller.go
pkg/neutronapi/const.go
templates/ovn-agent.conf
test/functional/base_test.go
test/functional/neutronapi_controller_test.go

OVN NB and SB DB connection strings are exported with this secret as these are required by neutron-ovn-agent[1].
[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/463
Related-Issue: [OSP-26191](https://issues.redhat.com//browse/OSP-26191)

Create EDP Secret for Neutron OVN Agent

---

controllers/neutronapi_controller.go
templates/neutronapi/config/01-neutron.conf

Segment plugin reports MissingAuthPlugin Exception when placement section is not configured, let's configure it.
Also Use ServicePassword consistantly as we use generic service user/password to talk to other services.
Related-Issue: [OSP-29953](https://issues.redhat.com//browse/OSP-29953)

Configure placement client

---

config/manifests/bases/neutron-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

controllers/neutronapi_controller.go
main.go
test/functional/suite_test.go

This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-10-19T12:08:39.421+0300    INFO    Controllers.NeutronAPI  Reconciling Service init        {"controller": "neutronapi", "controllerGroup": "neutron.openstack.org", "controllerKind": "NeutronAPI", "NeutronAPI": {"name":"neutron","namespace":"openstack"}, "namespace": "openstack", "name": "neutron", "reconcileID": "c1751493-7337-4c97-8af2-30cdb1a1e2fa"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.

switch to structured logging

---

controllers/neutronapi_controller.go
pkg/neutronapi/deployment.go
pkg/neutronapi/scc.go
pkg/neutronapi/volumes.go
templates/neutronapi/config/01-neutron.conf
templates/neutronapi/httpd/10-neutron-httpd.conf
templates/neutronapi/httpd/httpd.conf
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml

This patch introduces an additional sidecontainer for the NeutronAPI that is
supposed to ProxyPass requests to the neutron-api process behind. This will also solve the problem of tls-everywhere for Neutron, where the second segment is re-encrypted from the Route (created by the openstack operator) to the deployment.
* The httpd will serve requests on 9696, while the neutron-api service will be run locally on 9697
* httpd instance will be customized in a follow up patch to mount certificates and add the related ssl directives
Jira: [OSP-29184](https://issues.redhat.com//browse/OSP-29184)

Add httpd sidecontainer for the Neutron API

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml

Printing the status.networkAttachments instead of the spec part is more useful as it dumps pod IPs.

Include status.networkAttachments in PrinterColumns

---

pkg/neutronapi/dbsync.go
pkg/neutronapi/deployment.go
pkg/neutronapi/scc.go
pkg/neutronapi/volumes.go
templates/neutronapi/config/db-sync-config.json
templates/neutronapi/config/neutron-api-config.json
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml

This is to keep neutron-api in line with [1] until we decide otherwise.
Keeping kolla has several drawbacks, specifically:
1. allowPrivilegeEscalation has to be true for sudo.
2. dropCapabilities cannot be ALL because kolla_set_configs failed to change to root gid.
This patch may be revisited later if we decide to tighten privileges further by patching our kolla fork, or removing kolla completely from the startup path. For now, we'll have to stick to common approach.
The discussion over kolla place can be continued in jira [2].
[1] https://github.com/openstack-k8s-operators/docs/blob/main/service_config.md
[2] https://issues.redhat.com/browse/OSPRH-2240

    Reintroduce kolla into startup path for neutron-api

---

zuul.d/jobs.yaml

These job unnecessary runs on renovate prs, kuttl
jobs enough for those changes, this patch extends
the previous regex for these files.

Skip tempest job run for api/go.mod/sum changes

---

templates/neutronapi/httpd/10-neutron-httpd.conf
zuul.d/jobs.yaml

We need to pass original host from the API requests incomining to the neutron api server e.g. in order to have proper pagination links returned.
Closes: [OSPRH-3099](https://issues.redhat.com//browse/OSPRH-3099)

Set ProxyPreserveHost directive to "on" in the httpd container

---

.prow_ci.env
Dockerfile
Makefile

To make neutron-operator image to be compiled correctly for OpenShift with FIPS enabled.
Closes: #[OSPRH-3105](https://issues.redhat.com//browse/OSPRH-3105)

Build neutron-operator image in the FIPS compatible way

---

config/rbac/role.yaml
controllers/neutronapi_controller.go
go.mod
go.sum
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/tests/neutron_tls/01-assert.yaml

This is built on top of https://github.com/openstack-k8s-operators/neutron-operator/pull/296 and fixes functional test failures by adopting NewDatabaseWithNamespace.

Hardcode neutron database and database-account CR names to `neutron`

---

controllers/neutronapi_controller.go
templates/neutronapi/config/01-neutron.conf
templates/neutronapi/config/db-sync-config.json
templates/neutronapi/config/neutron-api-config.json
test/functional/base_test.go
test/functional/neutronapi_controller_test.go

The my.cnf file gets added to the secret holding the service configs. The content of my.cnf is centrally managed in the mariadb-operator and retrieved calling db.GetDatabaseClientConfig(tlsCfg)
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/190
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/191
Jira: [OSPRH-4547](https://issues.redhat.com//browse/OSPRH-4547)

[tlse] TLS database connection

---

templates/neutronapi/config/01-neutron.conf

Using localhost would allow bind_host to use the correct loopback address for ipv6.

Use bind_host=localhost

---

test/kuttl/common/scripts/check_debug_in_neutron_pod_logs.sh
test/kuttl/tests/change_neutron_config/01-assert.yaml
test/kuttl/tests/change_neutron_config/01-deploy-neutron.yaml
test/kuttl/tests/change_neutron_config/02-assert.yaml
test/kuttl/tests/change_neutron_config/03-assert.yaml
test/kuttl/tests/change_neutron_config/03-change_neutron_debug_config.yaml
test/kuttl/tests/change_neutron_config/04-cleanup-neutron.yaml
test/kuttl/tests/change_neutron_config/04-errors.yaml
test/kuttl/tests/change_neutron_config/deploy/kustomization.yaml

Implement a kuttl test to ensure that any modifications to the neutron service settings lead to the creation of a new pod with the updated settings. These tests should first confirm that the default logging setting excludes debug details. Then, after adjusting the neutron configuration to enable debug mode (debug = true), the tests should verify that the logs from the newly created pod now contain debug information.

Add kuttl test for neutron operator: change neutron debug config

---

api/v1beta1/neutronapi_types.go
api/v1beta1/neutronapi_webhook.go

Add the timeout property as required annotation for the Neutron API Route. This needs to be followed by a commit in openstack-operator since the route is defined there. In that commit the GetDefaultRouteAnnotations method is used accordingly.
(Goes together with https://github.com/openstack-k8s-operators/openstack-operator/pull/722)

Add default timeout for route annotations

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/go.mod
api/go.sum
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
controllers/neutronapi_controller.go
go.mod
go.sum
test/functional/neutronapi_controller_test.go

This patch follows the same pattern applied to the other operators, where we re-init the condition at each reconcile loop. `Conditions` are re-evaluated and updated, keeping the `LastTransitionTime` for those that haven't changed (it avoids the transition from True to Unknown to True again).
In addition, the `observedGeneration` field is introduced, and it is used by the `openstack-operator` to check the `IsReady()` function for a particular CR in case a minor update is triggered. All the conditions are evaluated during the main Reconcile loop ( or the `reconcileNormal` function in some circumstances), hence the main `ReadyCondition` is updated within the same flow.
The defer function still updates the `Resource` and mirrors the condition to the top-level `CR`.
Jira: …

Re-init conditions each reconcile

---

api/v1beta1/neutronapi_webhook.go

Add a *core* API spec version of the new
GetDefaultRouteAnnotations function. The new
OpenStackControlPlane PR will require use of this
version in order to leverage the same function.

Add *core* validation for default route annotations

---

zuul.d/jobs.yaml

https://github.com/openstack-k8s-operators/ci-framework/pull/1391 moves to test_operator role for running tempest tests. It broke the existing vars based on tempest role.
It also needs to be migrated to test_operator.
Let use tempest role here to bring back running tempest tests.

Switch to tempest role for running tempest

---

controllers/neutronapi_controller.go
test/functional/neutronapi_controller_test.go

`DeploymentReadyCondition` is something that depends on the number of ready `Replicas`, but it should also be influenced by the `ObservedGeneration`. We need to make sure that the readiness is set for the last `CR` version, and this patch adds the additional check that we're rolling out to the other operators as well.

Check Deployment ObservedGeneration to set ReadyCondition

---

controllers/neutronapi_controller.go

As per the agreement in [1], the controller should evaluate the current CR readiness only when the Generation matches with the ObservedGeneration. Any other edge case can be handled by a separate check, but we do not want to risk to reach "ReadyCondition = True" when we see a Generation "<" of the ObservedGeneration.
[1] https://github.com/openstack-k8s-operators/dev-docs/pull/102

Fix ObsGen condition check

---

controllers/neutronapi_controller.go
test/functional/neutronapi_controller_test.go

Fixed a missing condition that prevented the deployment from being marked as ready, even though all certificates and attached secrets were properly prepared.

[tlse] Ensure input readiness reported after all certificates are ready

---

.pre-commit-config.yaml
controllers/neutronapi_controller.go
pkg/neutronapi/const.go
pkg/neutronapi/scc.go
test/functional/base_test.go
test/functional/neutronapi_controller_test.go
test/functional/suite_test.go

* removed unused func params
* ignore revive dot-imports rule on ginkgo and gomega as dot import
there is the recommended practice
* various small style fixes found by the linter

Ensure golangci-lint runs on all files

---

controllers/neutronapi_controller.go

As per [1], errors should be uncapitalized, "since they are usually printed following other context".
While at it, replaced Ovn -> OVN in several error messages.
1: https://go.dev/wiki/CodeReviewComments

style: Uncapitalize error messages

---

controllers/neutronapi_controller.go

As per [1], we should avoid unnecessary indents in these cases.
```
Try to keep the normal code path at a minimal indentation, and indent
the error handling, dealing with it first.
```
1: https://go.dev/wiki/CodeReviewComments

style: Flip if-else order where it saves indent

---

.pre-commit-config.yaml

Add a new pre-commit check to avoid using more than one TestAssert in a
single kuttl assert file as that can lead to false positives as only the
last TestAssert is run by kuttl.
Fortunately there was no such issue in this repo.

o[pre-commit][kuttl]Check for multiple TestAsserts

---

config/manifests/bases/neutron-operator.clusterserviceversion.yaml

This change adds the feature flag to indicate that our operator is fips compliant.

Set fips-compliant CRD feature flag

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
api/v1beta1/neutronapi_webhook.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
controllers/neutronapi_controller.go
templates/neutronapi/config/01-neutron.conf
templates/neutronapi/config/neutron-api-config.json
test/functional/neutronapi_controller_test.go

The input passed to DefaultConfigOverwrite was not pushed to correct location where neutron api will use those.
Also limited the use of this parameter by webhook just to provide custom policy.yaml, can be extended if we need to support other files later. It follows same patter as placement and nova operator.
We already have "ExtraMounts" parameter which can be used to push arbitary files/directory in neutron-api pod.
Closes-Issue: [OSPRH-4298](https://issues.redhat.com//browse/OSPRH-4298)

Add missing bits for DefaultConfigOverwrite

---

config/manifests/bases/neutron-operator.clusterserviceversion.yaml

Removing:
`operators.openshift.io/infrastructure-features: ["disconnected"]` is deprecated starting with OpenShift 4.14
The `features.operators.openshift.io/disconnected: "true"` annotation is already present as its replacament
Adding newly required csv annotations. Set to "false" to indicate this operator does not support them
Implements: https://issues.redhat.com/browse/OSPRH-7921

Add required csv annotations. Remove deprecated

---

controllers/neutronapi_controller.go

Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler

Return nil error in case NotFound and to use RequeueAfter

---

controllers/neutronapi_controller.go
test/functional/neutronapi_controller_test.go

Use verifySecret to check for the specific password selector
Before this change the operator would trigger pod restart on any change in the secret. This is because the operator was looking at the overall hash of the secret. With this change, we only hash the secret data for the operator's password selector. This was most noticeable with the osp-secret which hosts multiple passwords for openstack operators. 
This PR also updates transportURL secret reconciliation to look for the `transport_url` password selector to stay consistent. However, the issue of pods restarting with secret update was not observed with transport url secret since we use a unique transport url secret for each operator. 
JIRA: [OSPRH-7992](https://issues.redhat.com//browse/OSPRH-7992)

Use verifySecret to check for the expected password selector

---

pkg/neutronapi/deployment.go
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml

This patch tunes the liveness and readiness probes to match other
operators [0][1][2][3].
We noticed that at times neutron tests would fail with 5XX errors,
indicating that the service was not avaiable during the execution of
the test, after investigation it was reported that neutron containers
were restarted due to probe failures.
Prior to this patch, neutron had the liveness and readiness probes set
to 5s where the majority of other operators had it set to something as
high as 30s (see links below).
This patch also removes the readiness probe from the neutron-api container
as it's redundant since it checks for readiness of the httpd container
(which is already checked by the httpd container readiness probe itself).
Resolves: https://issues.redhat.com/browse/OSPRH-9305
[0] …

Tune and enhance neutron-operator probes

---

test/kuttl/common/scripts/check_debug_in_neutron_pod_logs.sh
test/kuttl/tests/change_neutron_config/00-assert.yaml
test/kuttl/tests/change_neutron_config/00-test-resources.yaml
test/kuttl/tests/change_neutron_config/02-assert.yaml
test/kuttl/tests/change_neutron_config/02-extramounts.yaml

Added config override check for both secret and configmap.
Also update debug config check pod to filter only running containers.
Resolves: [OSPRH-4296](https://issues.redhat.com//browse/OSPRH-4296)

Add kuttl tests to validate config overrides with extraMounts

---

templates/neutronapi/config/01-neutron.conf

These are already the default values in upstream code.

refactor: Clean up some defaults from neutronapi config

---

pkg/neutronapi/deployment.go
pkg/neutronapi/scc.go
pkg/neutronapi/volumes.go
templates/neutronapi/config/neutron-api-config.json
templates/neutronapi/config/neutron-httpd-config.json
templates/neutronapi/httpd/httpd.conf
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/tests/neutron_tls/01-assert.yaml

This patch moves the `httpd` sidecar container under `kolla` management and by doing this we are able to not run it as root anymore, but use the same `NeutronUID`/`NeutronGID` provided for the `NeutronAPI` service.
Part of the conversation is tracked in Jira [1].
Jira: https://issues.redhat.com/browse/OSPRH-10290
[1] https://issues.redhat.com/browse/OSPRH-2240

Run neutron httpd sidecar container using NeutronUID

---

controllers/neutronapi_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

templates/neutronapi/httpd/10-neutron-httpd.conf

Neutron server returns links to the "next" and "previous" page of results when pagination is requested by client.
In the neutron-httpd container configuration there was an issue that "X-Forwarded-Proto" header was setting "https" protocol always, no matter if TLS was enabled in the deployment or not. It caused issues when TLS was disabled as client was doing request to the "http://" endoint and got in response "https://" links to "next" and "prev" pages.
This patch fixes this issue by setting correct protocol for both cases: TLS and non-TLS.
Closes-bug: [OSPRH-10632](https://issues.redhat.com//browse/OSPRH-10632)

Fix pagination links returned by neutron-server in non-TLS deployments

---

templates/neutronapi/config/01-neutron.conf

As we discussed on Slack and team meeting, it is enough to set only 'geneve' tunnel network type as tenant_network_types so that Neutron will be by default automatically trying to allocate tenant network segments only of the 'geneve' type.
Of course this value can be overwritten through the customServiceConfig provided by the Neutron CRD.
Closes: #[OSPRH-10781](https://issues.redhat.com//browse/OSPRH-10781)

Change default value of the 'tenant_network_types' option

---

templates/neutronapi/config/01-neutron.conf

As we don't support vxlan network type in the ML2/OVN backend in RHOSO we should not load by default vxlan type driver. This patch cleans it from the default Neutron config template.
Closes: #[OSPRH-10967](https://issues.redhat.com//browse/OSPRH-10967)

Remove vxlan config bits from the default configuration

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
api/v1beta1/neutronapi_webhook.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
controllers/neutronapi_controller.go
templates/neutronapi/httpd/10-neutron-httpd.conf
test/functional/neutronapi_controller_test.go

Added a parameter 'apiTimeout' to allow customization
to the Apache timeout.
The default is set to 120s which we do set for
HAProxy timeouts currently.
To be able to change the HAProxy value based on the `apiTimeout` with
any update (and not just the first time) the code adds a custom
annotation "api.neutron.openstack.org/timeout" with the value that was
initially set, this way flags it as being set by the neutron-operator.
There will be follow up patch in openstack-operator
to utilize the method 'SetDefaultRouteAnnotations' to set
these default route annotations.
Resolves: [OSPRH-10843](https://issues.redhat.com//browse/OSPRH-10843)

Make apache timeout configurable

---

api/go.mod
api/go.sum
controllers/neutronapi_controller.go
go.mod
go.sum

For BGP setup there is the need to set the default gateway to the additional interface defined via the multus annotations. To allow this a user can configure `ipam.gateway` in the NAD. EnsureNetworksAnnotation() will override the pod network default route by reading the NAD. If `ipam.gateway` is defined and not "", it gets set on the networks annotation as the `default-route`.
Jira: https://issues.redhat.com/browse/OSPRH-8680
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/579

Use new nad.EnsureNetworksAnnotation() func to get NAD annotations

---

api/v1beta1/neutronapi_types.go
api/v1beta1/zz_generated.deepcopy.go
pkg/neutronapi/dbsync.go
pkg/neutronapi/deployment.go
test/functional/neutronapi_controller_test.go

nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

Ensure nodeSelector logic is consistent for all operators

---

templates/neutronapi/httpd/10-neutron-httpd.conf

ocp routes add these header based on ssl config,
let's honor that and set this request header only in httpd config only if it's empty.
Noticed this issue with pagination tests when deployed control plane with tls.podlevel=false and tls.ingress=true.
Related-Issue: [OSPRH-12374](https://issues.redhat.com//browse/OSPRH-12374)

[httpd] Set X-Forwarded-Proto only if empty

---

templates/neutronapi/config/01-neutron.conf

The default switched in neutron master already with [1]. Setting it in operator default config to get it applied in older releases like antelope where [1] is not available.
[1] https://review.opendev.org/c/openstack/neutron/+/930608
Related-Issue: #[OSPRH-10684](https://issues.redhat.com//browse/OSPRH-10684)

Enable ovn_emit_need_to_frag by default

---

test/kuttl/tests/change_neutron_config/02-assert.yaml
test/kuttl/tests/change_neutron_config/03-assert.yaml

Couple of tests were relying on NEUTRON_KUTTL_DIR to be set, let's avoid the dep on extra var and use relative path to the test.
Alternative to https://github.com/openstack-k8s-operators/install_yamls/pull/915

[kuttl] Use relative path to scripts

---

templates/neutronapi/config/01-neutron.conf

Whenever one of the mecached pods disappears, because of a rolling restart during a minor update or as result of a failure, APIs can take a long time to detect that the pod went away and keep trying to reconnect.
From a quick round of tests we saw downtimes up to ~150s.
By tuning memcache_pool_dead_retry and memcache_pool_conn_get_timeout the behavior seems much more acceptable.
Since neutron also uses memcached directly we also need to tweak the [cache] section enabling the retry mechanism in the client and apply similar defaults.
Jira: https://issues.redhat.com/browse/OSPRH-11935

Configure keystonemiddleware/oslo to deal with memcached pods failures

---

.golangci.yaml
controllers/neutronapi_controller.go
pkg/neutronapi/const.go

Follow best practices for secure error and exception handling.
* Add err113 and gosec check in golang-ci-linter.
* Errors in neutron controller have been moved to a central file.
Resolve: https://issues.redhat.com/browse/OSPRH-9005

Improve error handling for neutron controller

---

test/functional/base_test.go
test/functional/neutronapi_controller_test.go

This patch improves our topology testing with several enhancements and extends the `topologyRef` tests:
- `finalizer` verification for each sub component that references a topology
- Updated `Topologies` to support `component-specific` label selectors
This work completes the topology validation improvements initiated in [1], addressing the remaining open points.
Jira: https://issues.redhat.com/browse/OSPRH-15220
[1] nova-operator#941

Improve topology testing coverage

---

templates/neutronapi/config/01-neutron.conf
test/functional/neutronapi_controller_test.go

In HA tests it was identified that pymemcache backend does not recover/fail over to the next memcache instance when one goes away unexpected. Using memcache_pool with bmemcache does failover properly.
The memcache_sasl_enable=true is a workaround to force oslo.cache to switch to the bmemcache driver, which is the only driver in memcache_pool supporting tls+fips.
Jira: [OSPRH-16651](https://issues.redhat.com//browse/OSPRH-16651)
Co-outhored-by: Luca Miccini <lmiccini@redhat.com>

Change memcache to use memcache_pool driver

---

test/functional/neutronapi_controller_test.go

This change uses GetDefaultMemcachedSpec test helper from infra-operator to reduce code duplication.

Use GetDefaultMemcachedSpec test helper from infra-operator

---

controllers/neutronapi_controller.go

Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16932](https://issues.redhat.com//browse/OSPRH-16932)

Do not update status when reconciler exits due to panic

---

controllers/neutronapi_controller.go
go.mod
go.sum
test/functional/neutronapi_controller_test.go

Adds watches of the Nova controller on the KeystoneAPI status to reconcile if e.g. the endpoint list changes. This triggers setting the new KeystoneAuthURL on the sub components to update their configuration.
Depends-On: https://github.com/openstack-k8s-operators/keystone-operator/pull/591
Jira: [OSPRH-16994](https://issues.redhat.com//browse/OSPRH-16994)

Watch KeystoneAPI status updates to reconcile

---

controllers/neutronapi_controller.go

The map ordering is random in golang[1], using
sort to make this deterministic and avoid any
reconcilation loops
[1] https://go.dev/blog/maps#iteration-order
Resolves: [OSPRH-17883](https://issues.redhat.com//browse/OSPRH-17883)

Sort map keys for deterministic iteration

---

controllers/neutronapi_controller.go

This change uses GetLogger instead of direct use of log.FromContext to support structured logging.

Use structured logging

---

templates/neutronapi/config/01-neutron.conf

This patch enables dns_records_ovn_owned when OVN is enabled by default to address slow DNS look up time.
Closes: #[OSPRH-10207](https://issues.redhat.com//browse/OSPRH-10207)

Enable dns_records_ovn_owned by default.
