README.md
cmd/manager/main.go
pkg/apis/neutron/v1/neutronovsagent_types.go
pkg/apis/neutron/v1/neutronsriovagent_types.go
pkg/controller/neutronovsagent/neutronovsagent_controller.go
pkg/controller/neutronsriovagent/neutronsriovagent_controller.go
pkg/neutronovsagent/configmap.go
pkg/neutronsriovagent/configmap.go
pkg/util/hosts.go
pkg/util/object_util.go
pkg/util/template_util.go

- reformat code with goimports
- add info about goimports into README

Format code with goimports

---

deploy/crds/neutron.openstack.org_ovsnodeosps_crd.yaml
pkg/apis/neutron/v1/ovsnnodeosp_types.go
templates/ovsnodeosp/ovsnode.sh

Use NIC to get IP for ovn encap ip

Correct ovs template to use NIC

---

README.md
cmd/manager/main.go
deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml
deploy/crds/neutron.openstack.org_ovncontrollers_crd.yaml
deploy/crds/neutron.openstack.org_ovsnodeosps_crd.yaml
go.mod
go.sum
tools/csv-generator.go

this adds new added OVNcontroller and OVSnodeOsp CRDs to the
csv-generator, also adds the scc generation as it is not handled
by olm correct.

Add OVNcontroller and OVSnodeOsp to cvs-generator

---

controllers/neutronapi_controller.go

Also sets init conditions and adds condition handling for `OVNConnectionConfigMap` processing

Mirror Keystone condition

---

templates/neutronapi/config/neutron.conf

These are also defaults in Director based deployments and provide some general functionalities.

Enable some supported plugins and extensions

---

.github/workflows/golangci-lint.yaml
.gitignore
Makefile
api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml

1. ensure that normal linting runs on the api module as well
2. introduce operator-lint [1] make target and run it in github workflow to check for operator development specific rule violations.
3. fix such violations
**Please note that this PR makes DatabaseInstance and Secret mandatory but it was optional before**
[1] https://github.com/gibizer/operator-lint

Lint improvements

---

controllers/neutronapi_controller.go
go.mod
go.sum

This will update SB/NB DB ips in neutron.conf if Status updates for OVNDBCluster Resources.
Signed-off-by: Yatin Karel <ykarel@redhat.com>

Add Watch to OVNDBCluster Resources

---

templates/neutronapi/config/db-sync-config.json

Drop logging.conf from db-sync too

---

test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/errors_cleanup_neutron.yaml

Recently the admin endpoint was removed, along with the service and
route, this changes removes them from the kuttl assert.

Adjust kuttl test for changes in endpoints

---

controllers/neutronapi_controller.go

We don't have to update a CR when the CR does not contain the finalizer being removed. This also removes some unused/redundant function from the Reconciler struct.

Skip redundant update when removing a finalizer

---

controllers/neutronapi_controller.go
pkg/neutronapi/const.go
templates/sriov-agent.conf
test/functional/neutronapi_controller_test.go

The name of the Secret is: neutron-sriov-agent-neutron-config

Create EDP config Secret for Neutron OVN SR-IOV Agent

---

README.md
api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
config/rbac/role.yaml
config/samples/neutron_v1beta1_neutronapi.yaml
controllers/neutronapi_controller.go
go.mod
main.go
templates/neutronapi/config/01-neutron.conf
test/functional/neutronapi_controller_test.go
test/functional/suite_test.go

Closes: [OSP-26502](https://issues.redhat.com//browse/OSP-26502)

Enable caching using memcached in the neutron server

---

templates/neutronapi/config/01-neutron.conf

Jira: #[OSPRH-1892](https://issues.redhat.com//browse/OSPRH-1892)

Enable new S-RBAC policies and scope enforcement by default in Neutron

---

Makefile

sync on skeleton based on operator-sdk init

standardize Makefile for operator-sdk usage

---

zuul.d/jobs.yaml
zuul.d/project.yaml

The job runs neutron tempest plugin api and scenario
tests.
Resolves: [OSPRH-679](https://issues.redhat.com//browse/OSPRH-679)

Add Tempest job in check pipeline

---

config/rbac/role.yaml
controllers/neutronapi_controller.go
go.mod
go.sum
test/functional/neutronapi_controller_test.go
test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/tests/neutron_tls/01-assert.yaml

This change bumps the mariadb-operator version and makes the necessary changes to work with the updated version.

Bump mariadb-operator version

---

config/manifests/bases/neutron-operator.clusterserviceversion.yaml

recent changes didn't update the CSV yaml file.
This updates to match what make bundle modifies things with

update CSV with tls

---

controllers/neutronapi_controller.go
templates/neutronapi/config/01-neutron.conf

Jira: [OSPRH-5283](https://issues.redhat.com//browse/OSPRH-5283)

Use tls for cache if supported

---

api/go.mod
api/go.sum
api/v1beta1/neutronapi_webhook.go
go.mod
go.sum
test/functional/neutronapi_controller_test.go

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505

Check for valid service override endpoint type on create and update

---

config/manifests/bases/neutron-operator.clusterserviceversion.yaml

if you generate make bundle
it will leave updated CSV file
This change came in with https://github.com/openstack-k8s-operators/neutron-operator/pull/354

update CSV with generated content

---

config/rbac/role.yaml
controllers/neutronapi_controller.go

We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363

Adding patch rbac perm for serviceaccounts

---

controllers/neutronapi_controller.go
test/functional/neutronapi_controller_test.go

JIRA: [OSPRH-7992](https://issues.redhat.com//browse/OSPRH-7992)
(cherry picked from commit f4a42cb48029262865d703e5d85dc4cecc969377)
Conflicts:
controllers/neutronapi_controller.go

[18.0.0-proposed] Use verifySecret to check for the expected password selector

---

test/kuttl/common/assert_sample_deployment.yaml
test/kuttl/common/errors_cleanup_neutron.yaml
test/kuttl/tests/neutron_tls/01-assert.yaml

To allow running tests with arbitary namespace.

[kuttl-tests] Remove hard coded namespace name

---

api/bases/neutron.openstack.org_neutronapis.yaml
api/v1beta1/neutronapi_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/neutron.openstack.org_neutronapis.yaml
config/samples/neutron_v1beta1_neutronapi_openvswitch.yaml
controllers/neutronapi_controller.go
pkg/neutronapi/deployment.go
templates/neutronapi/config/01-neutron.conf
test/functional/neutronapi_controller_test.go
test/kuttl/tests/neutron_no_ovn/01-assert.yaml
test/kuttl/tests/neutron_no_ovn/01-deploy-neutron.yaml
test/kuttl/tests/neutron_no_ovn/02-cleanup-neutron.yaml
test/kuttl/tests/neutron_no_ovn/02-errors.yaml
test/kuttl/tests/neutron_no_ovn/deploy/kustomization.yaml

Note to reviewers: I advise to ignore white space changes when reviewing Functional test changes.

Untangle service from ovn requirement

---

OWNERS_ALIASES

AFAIU there's not a single patch by @beagles in the repo.

OWNERS: drop beagles from approvers

---

controllers/neutronapi_controller.go

Add OVN cert validation to detect changes in `cert-neutron-ovndbs`. This patch includes the OVN cert hash in the combined TLS secrets hash.

[tls] Fix validate ovn service cert secret

---

templates/neutronapi/config/01-neutron.conf

Jira: [OSPRH-16651](https://issues.redhat.com//browse/OSPRH-16651)

Fix memcache_sasl_enable parameter to be memcache_sasl_enabled
